"""Stable semantic-role and processing-action vocabulary.

The strategy engines may provide evidence, but this module owns the shared
names.  It deliberately does not contain Paddle- or Manga-specific rules.
"""

from .result_contract import (
    PROCESSING_ACTION_PRESERVE,
    PROCESSING_ACTION_REVIEW,
    PROCESSING_ACTION_TRANSLATE_INPAINT,
    SEMANTIC_ROLE_AMBIGUOUS,
    SEMANTIC_ROLE_DECORATIVE,
    SEMANTIC_ROLE_DIALOGUE_BUBBLE,
    SEMANTIC_ROLE_DIALOGUE_FREE,
    SEMANTIC_ROLE_NARRATION,
    SEMANTIC_ROLE_SFX,
    SEMANTIC_ROLE_UI_OR_SIGN,
    VALID_PROCESSING_ACTIONS,
    VALID_SEMANTIC_ROLES,
)

__all__ = [
    "PROCESSING_ACTION_PRESERVE",
    "PROCESSING_ACTION_REVIEW",
    "PROCESSING_ACTION_TRANSLATE_INPAINT",
    "SEMANTIC_ROLE_AMBIGUOUS",
    "SEMANTIC_ROLE_DECORATIVE",
    "SEMANTIC_ROLE_DIALOGUE_BUBBLE",
    "SEMANTIC_ROLE_DIALOGUE_FREE",
    "SEMANTIC_ROLE_NARRATION",
    "SEMANTIC_ROLE_SFX",
    "SEMANTIC_ROLE_UI_OR_SIGN",
    "VALID_PROCESSING_ACTIONS",
    "VALID_SEMANTIC_ROLES",
]
